### ISSUE TITLE
ENC5 - multiple USB cameras

### ISSUE THREAD

**Issue by elisterr** [matiaspl/LinkPi-ENCx#11]
Hi, 

is there a way to expand the default amount of USB cameras that can connect and that can be encoded by the ENC encoder. 

By default its 1.  If I'm not currently using all the HDMI inputs then it would be nice to use extra USB cameras.
OR
Sometimes you need more HDMI inputs and I'd use a USB dock with multiple capture cards.

**Comment by matiaspl** [comment]
There might be support for that now, as the UVC2 device uses the same firmware.
