### ISSUE TITLE
Bricked ENC1V2?

### ISSUE THREAD

**Issue by theDaRkMaN1984** [matiaspl/LinkPi-ENCx#14]
Hey there!

I need some help with a LinkPi ENC1v2 Encoder. The Only thing i see is the logo on screen. After some research i tried to "flash" and reset it via USB stick but nothing happens. Still in a sort of boot loop. Which solutions do i have to get the thing back to life?

Greetings
Chris

**Comment by TJC** [comment]
That's odd, I've never see that. How did you brick it in the first place?

**Comment by theDaRkMaN1984** [comment]
i've updated the box with the newest firmware BEFORE updating the root update if you understand what i mean

**Comment by TJC** [comment]
I don't really understand, actually.

Umm. Maybe just make sure you're really following the instructions correctly for the USB flash method?
- Partitioned with a single MSDOS-style partition (not GPT type).
- FAT32 format (not exFAT, not NTFS, not APFS)
- Extract the files from the ZIP to the root.
- Hold down the reset button, then plug in power, and keep holding the reset button until it says "UPDATING" on the little screen.

**Comment by theDaRkMaN1984** [comment]
Okay.. back to the start.

Last time where i got connection to the Webinterface i choose the online update variant. there were two options. one with: download and one just with a "/". I select download and after the download i restarted the box via click on the button on the left side. after that it hangs on the boot screen. 

USB Flash Method which you described won't work. Looks like the box really hangs on bootup, because there is no recognition of anything. Even the LAN port isn't available.

I followed the steps with Rufus and with Windows (diskpart) directly but i don't know how long i should wait with holding the reset button but after 5 minutes i'd quit waiting.

**Comment by TJC** [comment]
> i don't know how long i should wait with holding the reset button but after 5 minutes i'd quit waiting.
Oh.. yeah, it's like 3 to 5 seconds

**Comment by theDaRkMaN1984** [comment]
Then i guess it hangs really ^_^

**Comment by theDaRkMaN1984** [comment]
hmmmm... just curiosity but for what is the RS 232 port? RS 232 means COM which is serial? There's no chance to go over there .. right?

**Comment by TJC** [comment]
I'm pretty sure the bootloader is only available on the internal serial port pins

**Comment by theDaRkMaN1984** [comment]
Hey TJC :)

Because i'm interested in IT and some hardware things i would try it on my own. Could i contact you here for some questions if i don't know what i should do? Of course i try to research possible ways to fix it on my own but for some special reasons :)

Thank you for your time :)

**Comment by theDaRkMaN1984** [comment]
Hey TJC!

Serial Output is:

 ```
                        

System startup

U-Boot 2010.06 (Jun 23 2020 - 14:23:02)

Check Flash Memory Controller v100 ... Found
SPI Nand(cs 0) ID: 0xc2 0x22 Name:"MX35LF2GE4AB"
Block:128KB Page:2KB Chip:256MB*1 OOB:64B ECC:4bit/512 
ECC provided by Flash Memory Controller
SPI Nand total size: 256MB
In:    serial
Out:   serial
Err:   serial
auto_update gpio
Hit any key to stop autoboot:  1  0 

NAND read: device 0 offset 0x500000, size 0x80000
 524288 bytes read: OK
i2c init
resetGpio
oled init 128x64

NAND read: device 0 offset 0x580000, size 0x80000
 524288 bytes read: OK
jpeg decoding ...
<<addr=0x83000000, size=0x80000, vobuf=0x83800000>>
mmu_enable
PicType: 6 ,Output Addr, Y: 83800000,UV: 839fe000
<<imgwidth=1920, imgheight=1080, linebytes=1920>>
decode success!!!!
decode jpeg!
stMaxRect.u32Width:1920, stMaxRect.u32Height:1080. 
HDMI_INFO:Hdmi_PixelFreqSearch[163] ,u32Fmt12. 
dev 0 opened!
video layer 0 opened!

NAND read: device 0 offset 0x100000, size 0x400000
 4194304 bytes read: OK
## Booting kernel from Legacy Image at 82000000 ...
   Image Name:   Linux-3.18.20
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5561632 Bytes = 5.3 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Loading Kernel Image ... OK
OK

Starting kernel ... 

```

Next Step please?

**Comment by theDaRkMaN1984** [comment]
Commando back. i tried the USB Flash method and the output said, that there's no USB Storage found. I don't know why, but i think the USB Port isn't working correctly because after using the MicroSD Card, formatted it at the exact way (FAT32 and so on), put the files from the ZIP in the root and hold reset while plug it in. Then updating appears. Now the Box is working :)

**Comment by TJC** [comment]
Congrats on fixing it!

**Comment by suom22** [comment]
Can someone tell me where to download the files that need to be placed on the SD card? , 

I can't find them

**Comment by TJC** [comment]
You can find the firmware downloads here:
https://gitee.com/LinkPi/Encoder/wikis/pages/preview?sort_id=2154092&doc_id=338777
