### ISSUE TITLE
How to Disable Telnet on 20231031

### ISSUE THREAD

**Issue by Gradinko** [matiaspl/LinkPi-ENCx#19]
I followed the directions in the wiki, but didn't see telnet listed anywhere in /etc/init.d/. To disable, I had to edit /link/config/service.json. This seems to be where the services are actually controlled:

`
/link/config # more service.json 
{
    "telnet":false,
    "ssh":true,
    "php":true,
    "nginx":true,
    "crond":true,
    "onvif":true,
    "ndi":true,
    "sls":true,
    "frp":false,
    "trans":false
}
`

**Comment by matiaspl** [comment]
I added your findings to the guide. Thanks!
