### ISSUE TITLE
Script to make your own oled boot logo

### ISSUE THREAD

**Issue by YveIce** [matiaspl/LinkPi-ENCx#22]
i have created a small python script to convert the logo.bin file to a .gif graphic and convert it back to binary format.
So you can create your own logo with any common image editing program like Gimp, Paint, Photoshop and so on.

maybe it's interesting for this big linkpi knowledge base.

https://github.com/YveIce/LinkPi-oled-logo-converter

**Comment by matiaspl** [comment]
Thanks, added to 3rd party tools section
