### ISSUE TITLE
Official Update

### ISSUE THREAD

**Issue by Audioman-Grado** [matiaspl/LinkPi-ENCx#3]
Hello, and sorry for my English, I'm Italian ...

Congratulations on the project, exactly what I was looking for.
I would like to ask a question: where do I find the official updates?

Thank you.

**Comment by matiaspl** [comment]
The official update firmwares can be found here:

https://gitee.com/LinkPi/Encoder/wikis/%E5%8D%87%E7%BA%A7&%E5%88%B7%E6%9C%BA/%E5%8D%87%E7%BA%A7%E5%8C%85

There are also versions that - judging by their size - are complete factory images (I personally haven't tried them, but I guess using them might result in full factory reset):

https://gitee.com/LinkPi/Encoder/wikis/%E5%8D%87%E7%BA%A7&%E5%88%B7%E6%9C%BA/%E5%88%B7%E6%9C%BA%E5%8C%85

You will need to register and login to Gitee using your Github account. If in doubt, use Chrome's built in translation engine.
